services:
  postgres:
    image: postgres:16-alpine
    container_name: search-postgres
    environment:
      POSTGRES_DB: searchdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d searchdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend/SearchEngineService
      dockerfile: Dockerfile
    container_name: search-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=searchdb;Username=postgres;Password=postgres
      Providers__JsonUrl: https://raw.githubusercontent.com/WEG-Technology/mock/refs/heads/main/v2/provider1
      Providers__XmlUrl: https://raw.githubusercontent.com/WEG-Technology/mock/refs/heads/main/v2/provider2
    ports:
      - "5018:5018"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/search-dashboard
      dockerfile: Dockerfile
    container_name: search-frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:5018
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
